name: Build project

on:
  push:
    branches:
      - main
      - dev

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64 standalone.
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Build with Unity
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

      - name: Send Discord notification on success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                    "username": "Build Bot",
                    "embeds": [{
                      "title": "✅ Build Succeeded!",
                      "description": "Build for **${{ matrix.targetPlatform }}** is complete.",
                      "color": 3066993,
                      "fields": [
                        {
                          "name": "Download",
                          "value": "[Click here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
                        }
                      ]
                    }]
                  }' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send Discord notification on failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                    "username": "Build Bot",
                    "embeds": [{
                      "title": "❌ Build Failed!",
                      "description": "Build for **${{ matrix.targetPlatform }}** has failed.",
                      "color": 15158332,
                      "fields": [
                        {
                          "name": "Check logs",
                          "value": "[View details](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
                        }
                      ]
                    }]
                  }' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
